import Head from "next/head";
import { useState } from "react";
import QRCode from "qrcode";
import Swal from "sweetalert2";
import withReactContent from "sweetalert2-react-content";

export default function Home() {
  const [url, setUrl] = useState("");
  const [qrcode, setQrcode] = useState("");
  const MySwal = withReactContent(Swal);

  const GenerateQRCode = () => {
    QRCode.toDataURL(
      url,
      {
        width: 800,
        margin: 2,
      },
      (err, url) => {
        if (err)
          return MySwal.fire({
            title: <p>Please, enter a valid text/url 👻</p>,
            icon: "error",
          });
        setQrcode(url);
      }
    );
  };

  return (
    <div>
      <Head>
        <title>QR Code Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <div className="flex justify-center pt-40">
            <div className="  flex flex-col justify-center">
              <h1 className=" text-3xl text-gray-900 font-semibold text-center mb-5">
                QR Code Generator
              </h1>

              <div className="flex flex-row">
                <input
                  className="bg-slate-100 placeholder-gray-400 focus:outline-none focus:outline-gray-300 text-gray-700"
                  type="text"
                  placeholder="e.g. https://http.cat"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                ></input>
                <button
                  className="rounded-md bg-green-500 text-gray-50 pl-4 pr-4 text-center hover:bg-green-400 hover:-translate-y-0.5 transform transition"
                  onClick={GenerateQRCode}
                >
                  Generate
                </button>
              </div>
              <div className="flex flex-col text-center mt-10 shadow-lg">
                {qrcode && (
                  <>
                    <img src={qrcode} />
                    <div className="">
                      <a
                        className="rounded-md bg-green-500 text-gray-50 py-5 px-5 text-center hover:bg-green-400 hover: transform transition"
                        href={qrcode}
                        download="qrcode.png"
                        target="_blank"
                      >
                        Download
                      </a>
                    </div>
                  </>
                )}
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
